apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv
spec:
  storageClassName: standard-rwo  # QUAN TRỌNG: Phải khớp với PVC của bạn
  capacity:
    storage: 10Gi                 # Phải lớn hơn hoặc bằng dung lượng PVC xin
  accessModes:
    - ReadWriteOnce
  hostPath:                       # Dùng ổ cứng của chính Node để lưu
    path: "/mnt/data/rabbitmq"    # Dữ liệu sẽ nằm ở đây trên Node
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq # Tên này sẽ là hostname để các backend kết nối (vd: amqp://user:password@rabbitmq:5672)
spec:
  ports:
    - port: 5672
      name: amqp
      targetPort: 5672
    - port: 15672
      name: management
      targetPort: 15672
      nodePort: 30080 # (Tùy chọn) Để truy cập dashboard từ bên ngoài
  selector:
    app: rabbitmq
  type: NodePort # Hoặc ClusterIP nếu không cần truy cập dashboard từ ngoài

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "user"
            - name: RABBITMQ_DEFAULT_PASS
              value: "password"
          volumeMounts:
            - name: rabbitmq-storage
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo
  resources:
    requests:
      storage: 1Gi